<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Promotion/Promotion.Application/Promotion.Application.csproj" />
    <ProjectReference Include="../../../src/Promotion/Promotion.Contracts/Promotion.Contracts.csproj" />
    <ProjectReference Include="../../../src/Promotion/Promotion.Domain/Promotion.Domain.csproj" />
    <ProjectReference Include="../../../src/Promotion/Promotion.Infrastructure/Promotion.Infrastructure.csproj" />
    <ProjectReference Include="../../../src/Promotion/Promotion.Worker/Promotion.Worker.csproj" />
  </ItemGroup>
</Project>
