<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Promotion.Contracts/Promotion.Contracts.csproj" />
    <ProjectReference Include="../Promotion.Domain/Promotion.Domain.csproj" />
  </ItemGroup>
</Project>
