<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Acceptance.Control</AssemblyName>
    <RootNamespace>Aggregator.Acceptance.Control</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Acceptance.Contracts/Acceptance.Contracts.csproj" />
    <ProjectReference Include="../../../src/Catalog/Catalog.Application/Catalog.Application.csproj" />
    <ProjectReference Include="../../../src/Catalog/Catalog.Infrastructure/Catalog.Infrastructure.csproj" />
  </ItemGroup>
</Project>
