<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Analytics.Contracts/Analytics.Contracts.csproj" />
    <ProjectReference Include="../Analytics.Domain/Analytics.Domain.csproj" />
  </ItemGroup>
</Project>
