<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Ingestion.Application/Ingestion.Application.csproj" />
    <ProjectReference Include="../Ingestion.Contracts/Ingestion.Contracts.csproj" />
    <ProjectReference Include="../Ingestion.Domain/Ingestion.Domain.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Platform.ObjectStorage/Platform.ObjectStorage.csproj" />
    <ProjectReference Include="../../BuildingBlocks/Platform.Persistence/Platform.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Catalog/Catalog.Contracts/Catalog.Contracts.csproj" />
  </ItemGroup>
</Project>
