<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Query.Domain/Query.Domain.csproj" />
    <ProjectReference Include="../Query.Contracts/Query.Contracts.csproj" />
    <ProjectReference Include="../../Catalog/Catalog.Contracts/Catalog.Contracts.csproj" />
    <ProjectReference Include="../../Promotion/Promotion.Contracts/Promotion.Contracts.csproj" />
  </ItemGroup>
</Project>
