<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Catalog.Contracts/Catalog.Contracts.csproj" />
    <ProjectReference Include="../Catalog.Domain/Catalog.Domain.csproj" />
    <ProjectReference Include="../Catalog.Media.Contracts/Catalog.Media.Contracts.csproj" />
  </ItemGroup>
</Project>
