using System.Reflection;
using System.Text;
using Aggregator.Catalog.Contracts;

namespace QueryProjectionAdapterGenerator;

internal static class Program
{
    private const string RelativeOutput =
        "src/Query/Query.Infrastructure/GeneratedCatalogPublicationProjectionAdapter.cs";

    public static int Main(string[] args)
    {
        var verify = args.Contains("--verify", StringComparer.Ordinal);
        var write = args.Contains("--write", StringComparer.Ordinal);
        if (verify == write)
        {
            Console.Error.WriteLine("Specify exactly one of --write or --verify.");
            return 2;
        }

        var repositoryRoot = FindRepositoryRoot();
        var output = repositoryRoot / RelativeOutput;
        var generated = Generate();
        if (write)
        {
            output.Directory.Create();
            File.WriteAllText(output.FullName, generated, new UTF8Encoding(false));
            Console.WriteLine($"Generated {RelativeOutput}.");
            return 0;
        }

        if (!output.Exists)
        {
            Console.Error.WriteLine($"Generated Query adapter is missing: {RelativeOutput}.");
            return 1;
        }

        var actual = File.ReadAllText(output.FullName);
        if (!string.Equals(actual, generated, StringComparison.Ordinal))
        {
            Console.Error.WriteLine(
                $"Generated Query adapter drift detected: {RelativeOutput}. Run the generator with --write.");
            return 1;
        }

        Console.WriteLine("Generated Query projection adapter is current.");
        return 0;
    }

    private static string Generate()
    {
        var eventType = typeof(CatalogPublicationActivated);
        var assembly = Assembly.Load("Query.Application");
        var candidates = assembly
            .GetExportedTypes()
            .Where(type => type.IsClass && !type.IsAbstract)
            .SelectMany(type => type
                .GetMethods(BindingFlags.Instance | BindingFlags.Public)
                .Where(method => method.DeclaringType == type)
                .Select(method => (Type: type, Method: method)))
            .Where(candidate =>
            {
                var parameters = candidate.Method.GetParameters();
                return parameters.Any(parameter => parameter.ParameterType == eventType) &&
                    parameters.All(parameter =>
                        parameter.ParameterType == eventType ||
                        parameter.ParameterType == typeof(CancellationToken)) &&
                    IsSupportedAwaitable(candidate.Method.ReturnType);
            })
            .OrderBy(candidate => candidate.Type.FullName, StringComparer.Ordinal)
            .ThenBy(candidate => candidate.Method.Name, StringComparer.Ordinal)
            .ToArray();
        if (candidates.Length != 1)
        {
            var names = candidates.Length == 0
                ? "none"
                : string.Join(
                    ", ",
                    candidates.Select(candidate =>
                        $"{candidate.Type.FullName}.{candidate.Method.Name}"));
            throw new InvalidOperationException(
                $"Expected exactly one public Query projection method accepting CatalogPublicationActivated and CancellationToken; found {names}.");
        }

        var selected = candidates[0];
        var arguments = string.Join(
            ", ",
            selected.Method.GetParameters().Select(parameter =>
                parameter.ParameterType == eventType
                    ? "publication"
                    : "cancellationToken"));
        var serviceType = selected.Type.FullName
            ?? throw new InvalidOperationException("Query projection service has no full name.");
        var invocation = $"service.{selected.Method.Name}({arguments})";
        return $$"""
        // <auto-generated />
        using Aggregator.Catalog.Contracts;
        using Aggregator.Query.Application;
        using Microsoft.Extensions.DependencyInjection;

        namespace Aggregator.Query.Infrastructure;

        /// <summary>Generated compile-time adapter from the producer event to the canonical Query projection service.</summary>
        public sealed class GeneratedCatalogPublicationProjectionAdapter(
            {{serviceType}} service) : IQueryCatalogPublicationHandler
        {
            public async Task HandleAsync(
                CatalogPublicationActivated publication,
                CancellationToken cancellationToken)
            {
                ArgumentNullException.ThrowIfNull(publication);
                await {{invocation}};
            }
        }

        public static class GeneratedQueryPublicationAdapterExtensions
        {
            public static IServiceCollection AddGeneratedQueryPublicationAdapter(
                this IServiceCollection services)
            {
                ArgumentNullException.ThrowIfNull(services);
                services.AddScoped<IQueryCatalogPublicationHandler,
                    GeneratedCatalogPublicationProjectionAdapter>();
                return services;
            }
        }
        """ + Environment.NewLine;
    }

    private static bool IsSupportedAwaitable(Type returnType) =>
        returnType == typeof(Task) ||
        returnType == typeof(ValueTask) ||
        (returnType.IsGenericType &&
         (returnType.GetGenericTypeDefinition() == typeof(Task<>) ||
          returnType.GetGenericTypeDefinition() == typeof(ValueTask<>)));

    private static DirectoryInfo FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null &&
               !File.Exists(Path.Combine(directory.FullName, "AggregatorBackend.slnx")))
        {
            directory = directory.Parent;
        }

        return directory
            ?? throw new InvalidOperationException("Aggregator repository root was not found.");
    }
}
