using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace QueryWorkerCompositionGenerator;

internal static class Program
{
    private const string RelativeOutput =
        "src/Query/Query.Worker/GeneratedQueryWorkerComposition.cs";

    public static int Main(string[] args)
    {
        var verify = args.Contains("--verify", StringComparer.Ordinal);
        var write = args.Contains("--write", StringComparer.Ordinal);
        if (verify == write)
        {
            Console.Error.WriteLine("Specify exactly one of --write or --verify.");
            return 2;
        }

        var repositoryRoot = FindRepositoryRoot();
        var output = new FileInfo(Path.Combine(repositoryRoot.FullName, RelativeOutput));
        var generated = Generate();
        if (write)
        {
            Directory.CreateDirectory(output.DirectoryName!);
            File.WriteAllText(output.FullName, generated, new UTF8Encoding(false));
            Console.WriteLine($"Generated {RelativeOutput}.");
            return 0;
        }

        if (!output.Exists)
        {
            Console.Error.WriteLine($"Generated Query worker composition is missing: {RelativeOutput}.");
            return 1;
        }

        if (!string.Equals(File.ReadAllText(output.FullName), generated, StringComparison.Ordinal))
        {
            Console.Error.WriteLine(
                $"Generated Query worker composition drift detected: {RelativeOutput}. Run with --write.");
            return 1;
        }

        Console.WriteLine("Generated Query worker composition is current.");
        return 0;
    }

    private static string Generate()
    {
        var assemblies = new[]
        {
            Assembly.Load("Query.Application"),
            Assembly.Load("Query.Infrastructure"),
        };
        var methods = assemblies
            .SelectMany(assembly => assembly.GetExportedTypes())
            .Where(type => type.IsAbstract && type.IsSealed)
            .SelectMany(type => type
                .GetMethods(BindingFlags.Public | BindingFlags.Static)
                .Where(method => method.IsDefined(typeof(ExtensionAttribute), inherit: false))
                .Select(method => (Type: type, Method: method)))
            .Where(candidate => candidate.Method.Name.StartsWith("AddQuery", StringComparison.Ordinal))
            .Where(candidate => candidate.Method.ReturnType == typeof(IServiceCollection))
            .Where(candidate => IsSupported(candidate.Method.GetParameters()))
            .OrderBy(candidate => candidate.Type.Assembly.GetName().Name, StringComparer.Ordinal)
            .ThenBy(candidate => candidate.Type.FullName, StringComparer.Ordinal)
            .ThenBy(candidate => candidate.Method.Name, StringComparer.Ordinal)
            .ToArray();
        if (methods.Length == 0)
        {
            throw new InvalidOperationException(
                "No supported AddQuery* IServiceCollection extension methods were found in Query Application/Infrastructure.");
        }

        var invocations = methods.Select(candidate =>
        {
            var declaringType = candidate.Type.FullName
                ?? throw new InvalidOperationException("A Query composition type has no full name.");
            var parameters = candidate.Method.GetParameters();
            var arguments = parameters.Length == 1
                ? "services"
                : "services, configuration";
            return $"        {declaringType}.{candidate.Method.Name}({arguments});";
        });
        return $$"""
        // <auto-generated />
        using Aggregator.Query.Application;
        using Aggregator.Query.Infrastructure;
        using Microsoft.Extensions.Configuration;
        using Microsoft.Extensions.DependencyInjection;

        namespace Aggregator.Query.Worker;

        public static class GeneratedQueryWorkerComposition
        {
            public static IServiceCollection AddGeneratedQueryWorkerComposition(
                this IServiceCollection services,
                IConfiguration configuration)
            {
                ArgumentNullException.ThrowIfNull(services);
                ArgumentNullException.ThrowIfNull(configuration);
        {{string.Join(Environment.NewLine, invocations)}}
                services.AddGeneratedQueryPublicationAdapter();
                return services;
            }
        }
        """ + Environment.NewLine;
    }

    private static bool IsSupported(ParameterInfo[] parameters) =>
        parameters.Length is 1 or 2 &&
        parameters[0].ParameterType == typeof(IServiceCollection) &&
        (parameters.Length == 1 || parameters[1].ParameterType == typeof(IConfiguration));

    private static DirectoryInfo FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null &&
               !File.Exists(Path.Combine(directory.FullName, "AggregatorBackend.slnx")))
        {
            directory = directory.Parent;
        }

        return directory
            ?? throw new InvalidOperationException("Aggregator repository root was not found.");
    }
}
