#!/usr/bin/env python3
"""Reconcile the physical .NET repository inventory with the canonical solution.

The script is deliberately deterministic and idempotent. It never invents projects:
it includes every existing src/tests project, rejects broken ProjectReference edges,
removes completion-session probes, and writes a reviewable inventory document.
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOLUTION = ROOT / "AggregatorBackend.slnx"
INVENTORY = ROOT / "docs" / "decisions" / "project-inventory.md"
PROJECT_REFERENCE_RE = re.compile(r'<ProjectReference\s+Include="([^"]+)"')


def normalize(path: pathlib.Path) -> str:
    return path.relative_to(ROOT).as_posix()


def discover_projects() -> list[pathlib.Path]:
    projects: list[pathlib.Path] = []
    for owner in (ROOT / "src", ROOT / "tests"):
        if owner.exists():
            projects.extend(owner.rglob("*.csproj"))
    return sorted({project.resolve() for project in projects}, key=normalize)


def verify_references(projects: list[pathlib.Path]) -> None:
    known = {project.resolve() for project in projects}
    failures: list[str] = []
    for project in projects:
        text = project.read_text(encoding="utf-8")
        for raw_reference in PROJECT_REFERENCE_RE.findall(text):
            target = (project.parent / raw_reference.replace("\\", "/")).resolve()
            if target not in known or not target.exists():
                failures.append(
                    f"{normalize(project)} -> {raw_reference} (resolved: {target})"
                )
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise RuntimeError(f"Broken ProjectReference edges:\n{joined}")


def folder_name(project: pathlib.Path) -> str:
    relative = project.relative_to(ROOT)
    parts = relative.parts
    if parts[0] == "src":
        if len(parts) < 3:
            raise RuntimeError(f"Project path has no bounded-context folder: {relative}")
        return f"/src/{parts[1]}/"
    if parts[0] == "tests":
        if len(parts) == 2:
            return "/tests/"
        return f"/tests/{parts[1]}/"
    raise RuntimeError(f"Project lies outside src/tests: {relative}")


def render_solution(projects: list[pathlib.Path]) -> str:
    grouped: dict[str, list[str]] = {}
    for project in projects:
        grouped.setdefault(folder_name(project), []).append(normalize(project))

    lines = ["<Solution>"]
    for folder in sorted(grouped, key=lambda value: (value.count("/"), value)):
        lines.append(f'  <Folder Name="{folder}">')
        for project in sorted(grouped[folder]):
            lines.append(f'    <Project Path="{project}" />')
        lines.append("  </Folder>")
    lines.append("</Solution>")
    return "\n".join(lines) + "\n"


def owner_from_project(project: pathlib.Path) -> str:
    parts = project.relative_to(ROOT).parts
    if parts[0] == "src":
        return parts[1]
    if parts[0] == "tests" and len(parts) > 2:
        return parts[1]
    return "Repository"


def project_sdk(project: pathlib.Path) -> str:
    try:
        root = ET.fromstring(project.read_text(encoding="utf-8"))
    except ET.ParseError as error:
        raise RuntimeError(f"Invalid project XML: {normalize(project)}: {error}") from error
    return root.attrib.get("Sdk", "(inherited)")


def render_inventory(projects: list[pathlib.Path], solution_text: str) -> str:
    digest = hashlib.sha256(solution_text.encode("utf-8")).hexdigest()
    by_owner: dict[str, list[pathlib.Path]] = {}
    for project in projects:
        by_owner.setdefault(owner_from_project(project), []).append(project)

    lines = [
        "# Physical project inventory",
        "",
        "This file is generated by `.tools/complete-backend.py`. It is the reviewable proof that every physical .NET project under `src/` and `tests/` is included in `AggregatorBackend.slnx`.",
        "",
        f"- Project count: **{len(projects)}**",
        f"- Canonical solution SHA-256: `{digest}`",
        "",
    ]
    for owner in sorted(by_owner):
        lines.extend([f"## {owner}", "", "| Project | SDK |", "|---|---|"])
        for project in sorted(by_owner[owner], key=normalize):
            lines.append(f"| `{normalize(project)}` | `{project_sdk(project)}` |")
        lines.append("")
    lines.extend(
        [
            "## Enforcement",
            "",
            "CI runs the reconciler in `--check` mode before restore. The check fails when a project is orphaned, a project reference is broken, the solution is non-canonical, or this inventory is stale.",
            "",
        ]
    )
    return "\n".join(lines)


def cleanup_probes() -> None:
    probe = ROOT / ".codex" / "probes" / "current-session.txt"
    if probe.exists():
        probe.unlink()
    parent = probe.parent
    if parent.exists() and not any(parent.iterdir()):
        parent.rmdir()


def write_or_check(path: pathlib.Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return False
    if check:
        print(f"stale: {normalize(path)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"updated: {normalize(path)}")
    return True


def main() -> int:
    check = "--check" in sys.argv[1:]
    cleanup_probes()
    projects = discover_projects()
    if not projects:
        raise RuntimeError("No .NET projects were discovered under src/ or tests/.")
    verify_references(projects)
    solution_text = render_solution(projects)
    inventory_text = render_inventory(projects, solution_text)
    stale = False
    stale |= write_or_check(SOLUTION, solution_text, check)
    stale |= write_or_check(INVENTORY, inventory_text, check)
    return 1 if check and stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
