#!/usr/bin/env python3
"""Reconcile physical .NET projects with the canonical full and runtime solutions.

The script is deterministic and idempotent. It never invents projects:
it includes every existing project under src/tests in the canonical solution,
includes every existing project under src in the runtime solution, rejects broken
ProjectReference edges, and writes a compact reviewable inventory summary.
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOLUTION = ROOT / "AggregatorBackend.slnx"
RUNTIME_SOLUTION = ROOT / "AggregatorBackend.Runtime.slnx"
INVENTORY = ROOT / "docs" / "decisions" / "project-inventory.md"
PROJECT_REFERENCE_RE = re.compile(r'<ProjectReference\s+Include="([^"]+)"')


def normalize(path: pathlib.Path) -> str:
    return path.relative_to(ROOT).as_posix()


def discover_projects() -> list[pathlib.Path]:
    projects: list[pathlib.Path] = []
    for owner in (ROOT / "src", ROOT / "tests"):
        if owner.exists():
            projects.extend(owner.rglob("*.csproj"))
    return sorted({project.resolve() for project in projects}, key=normalize)


def verify_references(projects: list[pathlib.Path]) -> None:
    known = {project.resolve() for project in projects}
    failures: list[str] = []
    for project in projects:
        text = project.read_text(encoding="utf-8")
        for raw_reference in PROJECT_REFERENCE_RE.findall(text):
            target = (project.parent / raw_reference.replace("\\", "/")).resolve()
            if target not in known or not target.exists():
                failures.append(
                    f"{normalize(project)} -> {raw_reference} (resolved: {target})"
                )
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise RuntimeError(f"Broken ProjectReference edges:\n{joined}")


def folder_name(project: pathlib.Path) -> str:
    relative = project.relative_to(ROOT)
    parts = relative.parts
    if parts[0] == "src":
        if len(parts) < 3:
            raise RuntimeError(f"Project path has no bounded-context folder: {relative}")
        return f"/src/{parts[1]}/"
    if parts[0] == "tests":
        if len(parts) == 2:
            return "/tests/"
        return f"/tests/{parts[1]}/"
    raise RuntimeError(f"Project lies outside src/tests: {relative}")


def render_solution(projects: list[pathlib.Path]) -> str:
    grouped: dict[str, list[str]] = {}
    for project in projects:
        grouped.setdefault(folder_name(project), []).append(normalize(project))

    lines = ["<Solution>"]
    for folder in sorted(grouped, key=lambda value: (value.count("/"), value)):
        lines.append(f'  <Folder Name="{folder}">')
        for project in sorted(grouped[folder]):
            lines.append(f'    <Project Path="{project}" />')
        lines.append("  </Folder>")
    lines.append("</Solution>")
    return "\n".join(lines) + "\n"


def digest(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def render_inventory(
    projects: list[pathlib.Path],
    runtime_projects: list[pathlib.Path],
    solution_text: str,
    runtime_solution_text: str,
) -> str:
    return "\n".join(
        [
            "# Physical project inventory",
            "",
            "This compact file is generated by `.tools/complete-backend.py`. The solution files are the canonical, exhaustive project lists; this document records their deterministic identities without duplicating every path.",
            "",
            f"- Complete projects: **{len(projects)}**",
            f"- Runtime projects: **{len(runtime_projects)}**",
            f"- Test projects: **{len(projects) - len(runtime_projects)}**",
            f"- Complete solution SHA-256: `{digest(solution_text)}`",
            f"- Runtime solution SHA-256: `{digest(runtime_solution_text)}`",
            "",
            "## Ownership",
            "",
            "- `AggregatorBackend.slnx` is the only complete solution owner.",
            "- `AggregatorBackend.Runtime.slnx` contains every project under `src/` and no test project.",
            "- Physical `.csproj` discovery and `ProjectReference` validation are performed directly from the repository tree.",
            "",
            "## Enforcement",
            "",
            "CI runs the reconciler in `--check` mode before any complete-solution restore. It fails on orphan projects, broken references, stale solution files, or a stale inventory identity.",
            "",
        ]
    )


def write_or_check(path: pathlib.Path, expected: str, check: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return False
    if check:
        print(f"stale: {normalize(path)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"updated: {normalize(path)}")
    return True


def main() -> int:
    check = "--check" in sys.argv[1:]
    projects = discover_projects()
    if not projects:
        raise RuntimeError("No .NET projects were discovered under src/ or tests/.")

    verify_references(projects)
    runtime_projects = [
        project for project in projects if project.relative_to(ROOT).parts[0] == "src"
    ]
    solution_text = render_solution(projects)
    runtime_solution_text = render_solution(runtime_projects)
    inventory_text = render_inventory(
        projects,
        runtime_projects,
        solution_text,
        runtime_solution_text,
    )

    stale = False
    stale |= write_or_check(SOLUTION, solution_text, check)
    stale |= write_or_check(RUNTIME_SOLUTION, runtime_solution_text, check)
    stale |= write_or_check(INVENTORY, inventory_text, check)
    return 1 if check and stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
