<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Acceptance.Contracts/Acceptance.Contracts.csproj" />
    <ProjectReference Include="../../../src/Ingestion/Ingestion.Collector.Contracts/Ingestion.Collector.Contracts.csproj" />
    <ProjectReference Include="../../../src/Analytics/Analytics.Contracts/Analytics.Contracts.csproj" />
    <ProjectReference Include="../../../src/Promotion/Promotion.Contracts/Promotion.Contracts.csproj" />
    <ProjectReference Include="../../../src/Query/Query.Contracts/Query.Contracts.csproj" />
  </ItemGroup>
</Project>
