<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Ingestion/Ingestion.Domain/Ingestion.Domain.csproj" />
    <ProjectReference Include="../../src/Ingestion/Ingestion.Contracts/Ingestion.Contracts.csproj" />
    <ProjectReference Include="../../src/Ingestion/Ingestion.Application/Ingestion.Application.csproj" />
    <ProjectReference Include="../../src/Ingestion/Ingestion.Infrastructure/Ingestion.Infrastructure.csproj" />
  </ItemGroup>
</Project>
